services:

  frontend:

    build:
      context: ./frontend

    container_name: transcendence-frontend

    working_dir: /app

    command: sh -c "npm run dev 2>&1 | tee /var/log/app/frontend.log"

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
      - app_logs:/var/log/app

    stdin_open: true
    tty: true
    init: true

    networks:
      - public-net
    
  backend:

    build:
      context: ./backend

    container_name: transcendence-backend

    depends_on:
      db:
        condition: service_healthy
    
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

    working_dir: /app

    command: sh -c "npm run start:dev 2>&1 | tee /var/log/app/backend.log"

    ports:
      - "3001:3000"

    volumes:
      - ./backend:/app:Z
      - /app/node_modules
      - app_logs:/var/log/app

    stdin_open: true
    tty: true
    init: true

    networks:
      - private-net

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', res => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5
  

  logs-init: # conteneur "jetable" : s'exécute une fois puis s'arrête
    image: docker.io/library/postgres:18-alpine
    command: sh -c "chmod 1777 /var/log/app" # ouvre le dossier en écriture pour tous, protégé par le sticky bit
    volumes:
      - app_logs:/var/log/app
  

  db:
    image: docker.io/library/postgres:18-alpine
    
    container_name: transcendence-db

    depends_on:
      restart: on-failure
    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    command: >
      postgres
      -c logging_collector=on
      -c log_directory=/var/log/app
      -c log_filename=db.log

    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    volumes:
      - db_data:/var/lib/postgresql
      - app_logs:/var/log/app

    networks:
      - private-net

  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0

    container_name: transcendence-elasticsearch

    environment:
      discovery.type: single-node         # une seule instance, pas de cluster
      xpack.security.enabled: "false"     # pas d authentification (réseau déjà isolé)
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"   # limite la RAM utilisée à 512 Mo
    
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
    
    volumes:
      - es_data:/usr/share/elasticsearch/data     # garde les données entre rédemarrages
    
    networks:
      - private-net
  
  logstash:

    image: docker.elastic.co/logstash/logstash:8.15.0
    
    container_name: transcendence-logstash

    depends_on:
      elasticsearch:
        condition: service_healthy

    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - app_logs:/var/log/app:ro

    networks:
      - private-net
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0

    container_name: transcendence-kibana

    environment:
       ELASTICSEARCH_HOSTS: http://elasticsearch:9200        # où aller chercher les données
    
    ports:
      - "5601:5601"

    networks:
      - private-net
  
  #vault:
    #image: hashicorp/vault:1.17

    #container_name: transcendence-vault

    #cap_add:
      #- IPC_LOCK # Ne pas faire du "swap" si la RAM est dépassée pour éviter une copie sur le disque dur
    
    #environment:
      
  prometheus:
    image: docker.io/prom/prometheus:v3.11.2

    container_name: transcendence-prometheus

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:Z
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:Z
      - prometheus_data:/prometheus

    ports:
      - "9090:9090"

    networks:
      - private-net

  grafana:
    image: docker.io/grafana/grafana:13.2.1

    container_name: transcendence-grafana

    depends_on:
      - prometheus

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:Z
      - grafana_data:/var/lib/grafana

    ports:
      - "3002:3000"

    networks:
      - private-net

  alertmanager:
    image: docker.io/prom/alertmanager:v0.32.0

    container_name: transcendence-alertmanager

    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:Z

    ports:
      - "9093:9093"

    networks:
      - private-net

volumes:
  db_data:
  es_data:
  prometheus_data:
  grafana_data:
  app_logs: # volume partage pour les logs

networks:
  public-net:
  private-net:
    # internal: true - à remettre une fois Nginx (WAF) sera le seul point d'entrée public
    # et que le backend n auta plus besoin de son 'ports' direct. 

