import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <section className="mx-auto w-full max-w-3xl flex-1 px-6 py-16">
      <h1 className="text-3xl font-semibold text-zinc-950">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-zinc-500">Last updated: August 28, 2026</p>

      <div className="mt-8 space-y-8 text-zinc-700">
        <div>
          <h2 className="text-lg font-semibold text-zinc-950">
            1. Purpose
          </h2>
          <p className="mt-2">
            Transcendix is a real-time multiplayer game in which several
            players compete to find a hidden Wikipedia page from word
            guesses, assisted by hints generated by artificial intelligence.
            Using the service implies acceptance of these terms.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-zinc-950">
            2. User account
          </h2>
          <p className="mt-2">
            You must provide accurate information when registering and are
            responsible for keeping your password confidential. An account
            is strictly personal and must not be shared.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-zinc-950">
            3. Game rules and conduct
          </h2>
          <p className="mt-2">
            It is forbidden to use scripts, bots, or any automated means to
            play on your behalf or to manipulate leaderboards. Messages sent
            in chat must remain respectful; any abusive, discriminatory, or
            harassing content may result in account suspension.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-zinc-950">
            4. Service availability
          </h2>
          <p className="mt-2">
            Transcendix is provided as part of an educational project. The
            service is provided &quot;as is&quot;, with no guarantee of
            continuous availability.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-zinc-950">
            5. Changes to these terms
          </h2>
          <p className="mt-2">
            These terms may be updated; the last modification date at the
            top of this page will be updated accordingly.
          </p>
        </div>
      </div>
    </section>
  );
}
