input {
  gelf {
    port => 12201                     # écoute les logs entrants au format GELF sur ce port
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]       # où envoyer ce qui a été reçu
    index => "docker-logs-%{+YYYY.MM.dd}"        # range par jour (un "tiroir" par date)
  }
}
